ProyectoFacturaDjango/djangoProyectoFactura/urls.py
from django.contrib import admin
from django.urls import path, include
import factura.views
from factura import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sistema/', include('factura.urls')),
    path('', views.login_request, name='login'),
    path('', views.index, name='index'),

]

handler404 = 'factura.views.handle_not_found'

ProyectoFacturaDjango/factura/urls.py
from django.urls import path
from django.contrib import admin

import factura.views
from factura import views

app_name = 'sistemafactura'

urlpatterns = [

    path('admin/', admin.site.urls, name='administracion'),
    path('sesion', views.sesion_iniciada, name='sesion_iniciada'),
    path('datos_empresa', views.datos_empresa, name='empresa'),
    path('facturas', views.facturas_hechas, name='facturas'),
    path('facturas/<int:factura_id>', views.factura_detalle, name='factura-id'),
    path('clientes', views.clientes, name='clientes'),
    path('productos', views.productos, name='productos'),
    path('inventario', views.inventario, name='inventario'),
    path('empleados', views.empleados, name='empleados'),
    path('logout', views.logout_request, name='salir'),
    path('agregar_producto', views.agregar_producto, name='agregar-producto'),
    path('modificar_producto/<id>/', views.modificar_producto, name='modificar-producto'),
    path('eliminar_producto/<id>/', views.eliminar_producto, name='eliminar-producto'),
    path('agregar_cliente', views.agregar_cliente, name='agregar-cliente'),
    path('modificar_cliente/<id>/', views.modificar_cliente, name='modificar-cliente'),
    path('eliminar_cliente/<id>/', views.eliminar_cliente, name='eliminar-cliente'),
    path('crear_factura', views.agregar_factura, name='crear-factura'),
    path('agregar_empleado', views.agregar_empleado, name='agregar-empleado'),
    path('modificar_empleado/<id>/', views.modificar_empleado, name='modificar-empleado'),
    path('eliminar_empleado/<id>/', views.eliminar_empleado, name='eliminar-empleado'),
    path('api', views.api_marvel, name='api-marvel'),

]



ProyectoFacturaDjango/factura/models.py
from django.db import models


class Persona(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    cedula = models.CharField(max_length=10)
    direccion = models.CharField(max_length=50, blank=True)
    telefono = models.CharField(max_length=10, blank=True)
    correo = models.CharField(max_length=25, blank=True)


class Empleado(Persona):
    cargo = models.CharField(max_length=20)

    def __str__(self):
        return self.nombre +" "+ self.apellido


class Cliente(Persona):
    def __str__(self):
        return self.nombre +" "+ self.apellido


class Empresa(models.Model):
    porcentajeIva = models.IntegerField()
    utilidad = models.IntegerField()
    nombre = models.CharField(max_length=50)
    ruc = models.CharField(max_length=13)
    telefono = models.CharField(max_length=10)
    correo = models.CharField(max_length=25)

    empleado_list = models.ManyToManyField('Empleado', blank=True, related_name='empresa')
    cliente_list = models.ManyToManyField('Cliente', blank=True, related_name='empresa')

    def __str__(self):
        return self.nombre


class Factura(models.Model):
    numero_factura = models.BigAutoField(primary_key=True, auto_created=True, serialize=False, verbose_name="No. ")
    monto_iva = models.FloatField(blank=True)
    fecha = models.DateField('Fecha', blank=False, null=False)
    sub_total = models.FloatField(editable=False, null=False, default=0)
    montoiva = models.FloatField(editable=False, null=False, default=0)
    valor_total = models.FloatField(editable=False, null=False, default=0)

    empresa = models.ForeignKey('Empresa', null=True, blank=True, on_delete=models.CASCADE, related_name='factura_list')
    cliente = models.ForeignKey('Cliente', null=True, blank=True, on_delete=models.CASCADE)
    detalle_list = models.ManyToManyField('DetalleFactura', blank=True, related_name='factura')

    def subtotal(self):
        subtotal = 0
        aux = self.detalle_list.all()
        for detalle in aux:
            aux2 = detalle.valor_total
            subtotal = aux2 + subtotal
            self.sub_total = subtotal
        return subtotal

    def monto_iva(self):
        monto_iva = self.subtotal() * (self.empresa.porcentajeIva/100)
        self.montoiva = monto_iva
        return monto_iva

    def total(self):
        total = self.monto_iva() + self.subtotal()
        self.valor_total = total
        return total
    
    def __str__(self):
        return "Factura No. "+str(self.numero_factura)


class DetalleFactura(models.Model):
    cantidad = models.IntegerField()
    producto = models.ForeignKey('Producto', null=True, blank=True, on_delete=models.CASCADE)

    @property
    def valor_total(self):
        valorTotal = self.cantidad * self.producto.precio_unitario
        return valorTotal

    @property
    def disminuir_stock(self):
        self.producto.stock = self.producto.stock - self.cantidad
        return self.producto.stock

    def __str__(self):
        return self.producto.nombre + " x " + str(self.cantidad)


class Producto(models.Model):
    nombre = models.CharField(max_length=50)
    detalle = models.CharField(max_length=100, blank=True, null=True)
    precioCompra = models.FloatField()
    stock = models.IntegerField()

    @property
    def precio_unitario(self):
        precio_unitario = self.precioCompra + (self.precioCompra * (25 / 100))
        return precio_unitario

    def __str__(self):
        return self.nombre


class Inventario(models.Model):
    producto_list = models.ManyToManyField('Producto', blank=True, related_name='inventario')
    empresa = models.ForeignKey('Empresa', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return "inventario"


ProyectoFacturaDjango/factura/forms.py
from django import forms
from factura.models import Producto, Cliente, Factura, DetalleFactura, Empleado


class ProductoForm(forms.ModelForm):

    class Meta:
        model = Producto
        fields = '__all__'


class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = '__all__'


class FacturaForm(forms.ModelForm):

    class Meta:
        model = Factura
        fields = '__all__'


class DetalleForm(forms.ModelForm):

    class Meta:
        model = DetalleFactura
        fields = '__all__'


class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = '__all__'


ProyectoFacturaDjango/factura/views.py
import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from factura.forms import ProductoForm, ClienteForm, FacturaForm, DetalleForm, EmpleadoForm
import requests, json

from factura.models import Factura, Cliente, Producto, Inventario, DetalleFactura, Empresa, Empleado


def index(request):
    return render(request, 'factura/index.html', {})


def sesion_iniciada(request):
    return render(request, 'factura/inicio.html', {})


def datos_empresa(request):
    empresa = Empresa.objects.first()
    context = {
        'empresa': empresa,
    }
    return render(request, 'factura/empresa.html', context)


def facturas_hechas(request):
    facturas = Factura.objects.all()
    context={
        'facturas': facturas,
    }
    return render(request, 'factura/facturas_hechas.html', context)


def clientes(request):
    clientes = Cliente.objects.all()
    context = {
        'clientes': clientes,
    }
    return render(request, 'factura/clientes.html', context)


def productos(request):
    productos = Producto.objects.all()
    context={
        'productos': productos,
    }
    return render(request, 'factura/productos.html', context)


def factura_detalle(request, factura_id):
    factura = get_object_or_404(Factura, pk=factura_id)
    context = {
        'factura': factura,
    }
    return render(request, 'factura/detalle_factura.html', context)


def inventario(request):
    productos = Producto.objects.all()
    context = {
        'productos': productos,
    }
    return render(request, 'factura/inventario.html', context)


def empleados(request):
    empleados = Empleado.objects.all()
    context = {
        'empleados': empleados,
    }
    return render(request, 'factura/empleados.html', context)


def agregar_producto(request):
    context = {
        'form': ProductoForm()
    }

    if request.method == 'POST':
        formulario  = ProductoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect("sistemafactura:productos")
        else:
            context["form"]=formulario

    return render(request, 'factura/agregar_producto.html', context)


def modificar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)

    context = {
        'form': ProductoForm(instance=producto)
    }
    if request.method == 'POST':
        formulario = ProductoForm(data=request.POST, instance=producto)
        if formulario.is_valid():
            formulario.save()
            return redirect("sistemafactura:productos")
        else:
            context["form"] = formulario
    return render(request, 'factura/modificar_producto.html', context)


def eliminar_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    producto.delete()
    return redirect("sistemafactura:productos")


def agregar_cliente(request):
    context = {
        'form': ClienteForm()
    }

    if request.method == 'POST':
        formulario = ClienteForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect("sistemafactura:clientes")
        else:
            context["form"]=formulario

    return render(request, 'factura/agregar_cliente.html', context)


def modificar_cliente(request, id):
    cliente = get_object_or_404(Cliente, id=id)

    context = {
        'form': ClienteForm(instance=cliente)
    }
    if request.method == 'POST':
        formulario = ClienteForm(data=request.POST, instance=cliente)
        if formulario.is_valid():
            formulario.save()
            return redirect("sistemafactura:clientes")
        else:
            context["form"] = formulario
    return render(request, 'factura/modificar_cliente.html', context)


def eliminar_cliente(request, id):
    cliente = get_object_or_404(Cliente, id=id)
    cliente.delete()
    return redirect("sistemafactura:clientes")


def agregar_empleado(request):
    context = {
        'form': EmpleadoForm()
    }

    if request.method == 'POST':
        formulario = EmpleadoForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect("sistemafactura:empleados")
        else:
            context["form"]=formulario

    return render(request, 'factura/agregar_empleado.html', context)


def modificar_empleado(request, id):
    empleado = get_object_or_404(Empleado, id=id)

    context = {
        'form': EmpleadoForm(instance=empleado)
    }
    if request.method == 'POST':
        formulario = EmpleadoForm(data=request.POST, instance=empleado)
        if formulario.is_valid():
            formulario.save()
            return redirect("sistemafactura:empleados")
        else:
            context["form"] = formulario
    return render(request, 'factura/modificar_empleado.html', context)


def eliminar_empleado(request, id):
    empleado = get_object_or_404(Empleado, id=id)
    empleado.delete()
    return redirect("sistemafactura:empleados")


def agregar_factura(request):
    context = {
        'form': FacturaForm(),
    }

    if request.method == 'POST':
        formulario = FacturaForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect("sistemafactura:facturas")
        else:
            context["form"]=formulario

    return render(request, 'factura/agregar_factura.html', context)


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            usuario = form.cleaned_data.get('username')
            contrasenia = form.cleaned_data.get('password')
            user = authenticate(username=usuario, password=contrasenia)
            if user is not None:
                login(request, user)
                return redirect("sistema/sesion")
            else:
                messages.error(request, 'Usuario o contraseña equivocada')
        else:
            messages.error(request, 'Usuario o contraseña equivocada')

    form = AuthenticationForm()
    return render(request, 'factura/index.html', {"form": form})


def logout_request(request):
    logout(request)
    messages.info(request, "Saliste de la sesión")
    return redirect("index")


def api_marvel(request):
    url = "https://gateway.marvel.com:443/v1/public/characters?apikey=e62cba377e616fcc381c12dd67e4f4f7&hash=0828b588b9a67f9a02c6381f0a39de44&ts=1"
    response = requests.get(url)
    response_json = json.loads(response.text)
    personajes = response_json["data"]["results"]
    context = {
        'personajes': personajes,
    }
    return render(request, 'factura/api.html', context)



def handle_not_found(request, exception):
    return render(request, 'factura/pag_no_encontrada.html')

ProyectoFacturaDjango/templates/factura/agregar_cliente.html
{% extends 'factura/base2.html' %}

{%  block titulo %}Agregar Cliente{% endblock %}

{% block contenido %}
    <br>
    <div class="div_paginas">

        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card">

                    <div class="card-body">
                        <h3 align="center">Agregar Nuevo Cliente</h3>
                        <hr>

                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}


                            <div class="d-flex justify-content-end">
                                <input type="submit" value="Agregar" class="btn btn-primary">
                                &nbsp;
                                <a href="{% url 'sistemafactura:clientes' %}" class="btn btn-danger">Cancelar</a>
                            </div>
                        </form>
                        {{ mensaje }}

                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

ProyectoFacturaDjango/templates/factura/agregar_empleado.html
{% extends 'factura/base2.html' %}

{%  block titulo %}Agregar Empleado{% endblock %}

{% block contenido %}
    <br>
    <div class="div_paginas">

        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card">

                    <div class="card-body">
                        <h3 align="center">Agregar Nuevo Empleado</h3>
                        <hr>

                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}


                            <div class="d-flex justify-content-end">
                                <input type="submit" value="Agregar" class="btn btn-primary">
                                &nbsp;
                                <a href="{% url 'sistemafactura:empleados' %}" class="btn btn-danger">Cancelar</a>
                            </div>
                        </form>
                        {{ mensaje }}

                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

ProyectoFacturaDjango/templates/factura/agregar_factura.html
{% extends 'factura/base2.html' %}

{%  block titulo %}Crear Factura{% endblock %}

{% block contenido %}
    <br>
    <div class="div_paginas">

        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card">

                    <div class="card-body">
                        <h3 align="center">Crear Nueva Factura</h3>
                        <hr>

                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}


                            <div class="d-flex justify-content-end">
                                <input type="submit" value="Agregar" class="btn btn-primary">
                                &nbsp;
                                <a href="{% url 'sistemafactura:facturas' %}" class="btn btn-danger">Cancelar</a>
                            </div>
                        </form>
                        {{ mensaje }}

                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

ProyectoFacturaDjango/templates/factura/agregar_producto.html
{% extends 'factura/base2.html' %}

{%  block titulo %}Agregar Producto{% endblock %}

{% block contenido %}
    <br>
    <div class="div_paginas">

        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card">

                    <div class="card-body">
                        <h3 align="center">Agregar Nuevo Producto</h3>
                        <hr>

                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}


                            <div class="d-flex justify-content-end">
                                <input type="submit" value="Agregar" class="btn btn-primary">
                                &nbsp;
                                <a href="{% url 'sistemafactura:productos' %}" class="btn btn-danger">Cancelar</a>
                            </div>
                        </form>
                        {{ mensaje }}

                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

ProyectoFacturaDjango/templates/factura/api.html
{% extends 'factura/base2.html' %}

{%  block titulo %}API Marvel{% endblock %}

{% block contenido %}
    <div class="div_paginas">
    <h3 align="center">Personajes de Marvel</h3>
    <p align="center">(Hacer click a las imágenes para más información del personaje)</p>

    <div style="width: 1500px; margin-left: auto;margin-right: auto; margin-bottom: 50px">
        {% for personaje in personajes %}
        <div style="width: 300px; height: 400px;float: left; margin: 30px">
            <a href="{{ personaje.urls.0.url }}">
                <img src="{{ personaje.thumbnail.path }}.{{ personaje.thumbnail.extension }}" class="img-thumbnail">
            </a>
            <h4>{{ personaje.name }}</h4>
        </div>
    {% endfor %}
    </div>


    </div>
{% endblock %}

ProyectoFacturaDjango/templates/factura/clientes.html
{% extends 'factura/base2.html' %}

{%  block titulo %}Clientes{% endblock %}

{% block contenido %}
    <div class="div_paginas">
        <h3 align="center">Clientes</h3>
        <div style="margin-left: 30px">
            <a href="{% url 'sistemafactura:agregar-cliente' %}" class="btn btn-primary" id="boton_personalizado">Agregar Cliente</a>
        </div>
        {% for cliente in clientes %}
            <div class="card" id="card_personalizada">
                  <div class="card-body">
                    <h5 class="card-title">{{ cliente.nombre }} {{ cliente.apellido }}</h5>
                    <p class="card-text">Cedula: {{ cliente.cedula }}</p>
                    <p class="card-text">Teléfono: {{ cliente.telefono }}</p>
                    <p class="card-text">Dirección: {{ cliente.direccion }}</p>
                    <p class="card-text">Correo: {{ cliente.correo }}</p>
                    <a href="{% url 'sistemafactura:modificar-cliente' cliente.id %}" class="btn btn-primary btn-sm">Modificar</a>
                    <a href="{% url 'sistemafactura:eliminar-cliente' cliente.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                  </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

ProyectoFacturaDjango/templates/factura/empleados.html
{% extends 'factura/base2.html' %}

{%  block titulo %}Empleados{% endblock %}

{% block contenido %}
    <div class="div_paginas">
        <h3 align="center">Empleados</h3>
        <div style="margin-left: 30px">
           <a href="{% url 'sistemafactura:agregar-empleado' %}" class="btn btn-primary" id="boton_personalizado">Agregar Empleado</a>
        </div>
        {% for empleado in empleados %}
            <div class="card" id="card_personalizada">
                  <div class="card-body">
                    <h5 class="card-title">{{ empleado.nombre }} {{ empleado.apellido }}</h5>
                    <p class="card-text">Empleado ID: {{ empleado.id }}</p>
                    <p class="card-text">Cedula: {{ empleado.cedula }}</p>
                    <p class="card-text">Cargo: {{ empleado.cargo }}</p>
                    <a href="{% url 'sistemafactura:modificar-empleado' empleado.id %}" class="btn btn-primary btn-sm">Modificar</a>
                    <a href="{% url 'sistemafactura:eliminar-empleado' empleado.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                  </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

ProyectoFacturaDjango/templates/factura/index.html
{% extends 'factura/base.html' %}
{% load static %}

{%  block titulo %}Iniciar Sesión{% endblock %}

{% block contenido %}
    <div align="center" style="margin-top: 20px">
        <img src="{% static 'imagenes/usuario.png' %}" alt="usuario" style="padding-bottom: 35px; margin-top: 30px" width=20%>
        <form method="POST">
            {% csrf_token %}

            <div class="form-group" style="width: 25%">
                <label>Nombre de usuario</label>
                <input type="text" class="form-control" placeholder="Nombre de usuario" name="username">
            </div>

            <div class="form-group" style="width: 25%">
                <label>Contraseña</label>
                <input type="password" class="form-control" placeholder="Contraseña" name="password">
            </div><br>

            <button type="submit" class="btn btn-primary">Iniciar Sesión</button>

            {% if messages %}
                <div id="mensaje">
                    <ul class="messages">
                        {% for message in messages %}
                            <p{% if message.tags %} class="{{ message.tags }}"{% endif %} align="center">{{ message }}</p>
                        {% endfor %}
                    </ul>
                </div>
            {% endif %}

        </form>
    </div>
{% endblock %}

ProyectoFacturaDjango/templates/factura/inicio.html
{% extends 'factura/base2.html' %}

{%  block titulo %}Sistema de Facturación{% endblock %}

{% block contenido %}


    <div style="float: left">


        <div class="card" id="card_personalizada">
          <img src="https://glenndoman.ec/wp-content/uploads/2022/03/laura-rivera-ArH3dtoDQc0-unsplash-1110x630.jpg" class="card-img-top" width="20%">

          <div class="card-body">
            <h5 class="card-title" align="center">Productos</h5>
            <a href="{% url 'sistemafactura:productos' %}" class="btn btn-primary">Ir a Productos</a>
          </div>
        </div>

        <div class="card" id="card_personalizada">
          <img src="https://blog.comparasoftware.com/wp-content/uploads/2021/02/tipos-de-clientes-de-ecommerce-1.png" class="card-img-top" width="20%">

          <div class="card-body">
            <h5 class="card-title" align="center">Clientes</h5>
            <a href="{% url 'sistemafactura:clientes' %}" class="btn btn-primary">Ir a Clientes</a>
          </div>
        </div>


        <div class="card" id="card_personalizada">
          <img src="https://uploads-ssl.webflow.com/60c3cc2547e9a6d51a61b5aa/60dc741bd7dea4931b680dae_facturas-p-1080.png" class="card-img-top" width="20%">

          <div class="card-body">
            <h5 class="card-title" align="center">Facturas</h5>
            <a href="{% url 'sistemafactura:facturas' %}" class="btn btn-primary">Ir a Facturas</a>
          </div>
        </div>



        <div class="card" id="card_personalizada">
          <img src="https://uploadgerencie.com/imagenes/inventario-costo.png" class="card-img-top" height=223px>

          <div class="card-body">
            <h5 class="card-title" align="center">Inventario</h5>
            <a href="{% url 'sistemafactura:inventario' %}" class="btn btn-primary">Ir a Inventario</a>
          </div>
        </div>

    </div>

    <div>
        {% if user.is_superuser != False %}
            <div>
                <div class="card" id="card_personalizada">
                    <img src="https://s3.amazonaws.com/wp-mpro/wp-content/uploads/2017/11/08070504/s3-programa-para-papelerias-share-fb.png" class="card-img-top">

                    <div class="card-body">
                        <h5 class="card-title" align="center">Empleados</h5>
                        <a href="{% url 'sistemafactura:empleados' %}" class="btn btn-primary">Ir a Empleados</a>
                    </div>
                </div>
            </div>
        {% endif %}

        <div>
            <div class="card" id="card_personalizada">
                <img src="https://i2.wp.com/www.gameoverla.com/wp-content/uploads/2019/01/3e2d91928fe9aeecf82c1fc959397394.jpg?fit=910%2C512&ssl=1" class="card-img-top" height=210px>

                    <div class="card-body">
                        <h5 class="card-title" align="center">API Marvel</h5>
                        <a href="{% url 'sistemafactura:api-marvel' %}" class="btn btn-primary">Ir a API</a>
                    </div>
            </div>
        </div>
    </div>

{% endblock %}

ProyectoFacturaDjango/templates/factura/inventario.html
{% extends 'factura/base2.html' %}

{%  block titulo %}Inventario{% endblock %}

{% block contenido %}
    <div class="div_paginas">
        <h3 align="center">Inventario</h3>
            <div id="tabla_inventario">
                <table>
                <thead>
                    <tr>
                        <th>Producto</th><th>Descripción</th><th>ID</th><th>Precio de compra</th><th>P.V.P</th><th>Stock</th>
                    </tr>
                </thead>
                {% for producto in productos %}
                    <tr>
                    <td>{{ producto.nombre }}</td><td>{{ producto.detalle }}</td><td>{{ producto.id }}</td><td>${{ producto.precioCompra}}</td><td>${{ producto.precio_unitario}}</td><td>{{ producto.stock}} unidades</td>
                    </tr>
                {% endfor %}
            </table>
            </div>

    </div>
{% endblock %}

ProyectoFacturaDjango/templates/factura/modificar_cliente.html
{% extends 'factura/base2.html' %}

{%  block titulo %}Editar Cliente{% endblock %}

{% block contenido %}
    <br>
    <div class="div_paginas">

        <div class="row">
            <div class="col-12 col-md-6 offset-md-3">
                <div class="card">

                    <div class="card-body">
                        <h3 align="center">Editar Cliente</h3>
                        <hr>

                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}


                            <div class="d-flex justify-content-end">
                                <input type="submit" value="Editar" class="btn btn-primary">
                                &nbsp;
                                <a href="{% url 'sistemafactura:clientes' %}" class="btn btn-danger">Cancelar</a>
                            </div>
                        </form>
                        {{ mensaje }}

                    </div>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

ProyectoFacturaDjango/templates/factura/pag_no_encontrada.html
{% extends 'factura/base.html' %}
{% load static %}

{%  block titulo %}Página no encontrada{% endblock %}

{% block contenido %}
    <div align="center" style="margin-top: 20px">
        <h3>UPSSSS</h3>
        <h3>Página no encontrada</h3>
        <a href="{% url 'sistemafactura:sesion_iniciada' %}">Volver a Inicio</a>
    </div>
{% endblock %}

ProyectoFacturaDjango/templates/factura/productos.html
{% extends 'factura/base2.html' %}

{%  block titulo %}Productos{% endblock %}

{% block contenido %}
    <div class="div_paginas">
        <h3 align="center">Productos</h3>
        <div style="margin-left: 23%">
            <a href="{% url 'sistemafactura:agregar-producto' %}" class="btn btn-primary" id="boton_personalizado">Agregar Producto</a>
        </div>
            <div id="tabla">
                <table>
                <thead>
                    <tr>
                        <th>Producto</th><th>Descripción</th><th>P.V.P</th><th>Opciones</th>
                    </tr>
                </thead>
                {% for producto in productos%}
                    <tr>
                    <td>{{ producto.nombre }}</td><td>{{ producto.detalle }}</td><td>${{ producto.precio_unitario }}</td>
                        <td>
                            <a href="{% url 'sistemafactura:modificar-producto' producto.id %}" class="btn btn-primary btn-sm">Modificar</a>
                            <a href="{% url 'sistemafactura:eliminar-producto' producto.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            </div>
        <h3 align="center" style="margin-top: 50px">Venta de los productos</h3>
        <div class="div_tabla_productos_vendidos">
            {% for producto in productos %}
                <p>{{ producto.nombre }}</p>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" aria-label="Basic example" style="width: {{ producto.stock }}%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}